######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = client
DEPENDPATH += .
INCLUDEPATH += src
DESTDIR = bin
OBJECTS_DIR = obj

# Input
SOURCES += src/main.cpp
SOURCES += src/Client.cpp
