######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = client
DEPENDPATH += .
INCLUDEPATH += src
INCLUDEPATH += /usr/local/Trolltech/Qt-4.5.2/include/QtNetwork
DESTDIR = bin
OBJECTS_DIR = obj
LIBS = -lQtNetwork

# Input
SOURCES += src/main.cpp
SOURCES += src/Client.cpp
