######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
DESTDIR = bin
OBJECTS_DIR = obj
MOC_DIR = obj
LIBS = -lcppunit -lQtNetwork
CONFIG += qt warn_on debug
 
# Input
SOURCES += hello/hello.cpp
