######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = TestClient
DEPENDPATH += .
INCLUDEPATH += src /usr/local/Trolltech/Qt-4.5.2/include/QtNetwork
HEADERS = src/Client.h
DESTDIR = bin
OBJECTS_DIR = obj
LIBS = -lcppunit -lQtNetwork
CONFIG += qt warn_on debug
 
# Input
SOURCES += test/test.cpp src/Client.cpp
