######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += src
DESTDIR = bin
OBJECTS_DIR = obj

# Input
SOURCES += test/test.cpp
SOURCES += src/client.cpp
