
DIR = debug
LIB = debug
SRCS = 	debug.cpp 

EXTRA_INCLUDES 	+= -Iinclude \
			-I$(SRCROOT)/color/include

EXTRALIBPATHS	+= $(BLDROOT)/$(MTARGET)/lib 


include $(MAKE_HOME)/makefile.incl
include $(MAKE_HOME)/makefile.lib

