#!/bin/sh

ORIENTATION=`cat config/orientation`

if [ "$ORIENTATION" = "HORIZ" ] ; then
    echo 'VERT' > config/orientation
    echo '-9 0 0' > config/coord
    echo 'VERT'
    exit
fi

if [ "$ORIENTATION" = "VERT" ] ; then
    echo 'HORIZ' > config/orientation
    echo '0 -9 0' > config/coord
    echo 'HORIZ'
    exit
fi

