######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = TestClient
DEPENDPATH += .

INCLUDEPATH += src /usr/local/Trolltech/Qt-4.5.2/include/QtNetwork
INCLUDEPATH += ../../wapserver3/cpp ../../wapserver3/cpp/libs ../../wapserver3/cpp/libs/header

HEADERS = src/Client.h test/TestClientLogin.h test/TestClientRegisterUser.h test/TestClientTable.h
DESTDIR = bin
OBJECTS_DIR = obj
MOC_DIR = obj
LIBS = -lcppunit -lQtNetwork
CONFIG += qt warn_on debug
 
# Input
SOURCES += test/test.cpp src/Client.cpp
