CREATE DATABASE IF NOT EXISTS WapServer3DB;
GRANT ALL PRIVILEGES ON WapServer3DB.* TO 'WapServer3'@'localhost' IDENTIFIED BY 'win74' WITH GRANT OPTION;
GRANT ALL ON WapServer3DB.* TO WapServer3@localhost;
FLUSH PRIVILEGES;