all: 
	cd src; make 

socketserver: 
	cd src/socketserver; make

tablemanager: 
	cd src/tablemanager; make

chatserver: 
	cd src/chatserver; make

chesserver: 
	cd src/chessserver; make

clean:
	cd src; make clean
