#!/bin/bash

PROGERS=( hukka ssadovni npavlenk ocheredn )

#find common/ -name '*.hpp' | xargs svn blame >> huge
#find common/ -name '*.cpp' | xargs svn blame >> huge

echo  " "

for ((i=0; i<${#PROGERS[*]}; i++))
do
   LINES=`cat huge | grep  ${PROGERS[$i]} | wc -l`
   echo ${PROGERS[$i]}    $LINES
done

echo  " "

rm huge