######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 15:38:00 2009
######################################################################

TEMPLATE = app
TARGET = TestClient
DEPENDPATH += .
INCLUDEPATH += src
DESTDIR = bin
OBJECTS_DIR = obj
LIBS = -lcppunit

# Input
SOURCES += test/test.cpp
SOURCES += src/Client.cpp
