all: 
	cd socketserver; make 
	cd tablemanager; make 
	cd chatserver; make 
	cd chessserver; make 

socketserver: 
	cd socketserver; make

tablemanager: 
	cd tablemanager; make

chatserver: 
	cd chatserver; make

chesserver: 
	cd chessserver; make

clean:
	cd socketserver; make clean
	cd tablemanager; make clean
	cd chatserver; make clean
	cd chessserver; make clean
