DIR = temp
EXE = temp
SRCS = 	temp.cpp 

EXTRA_INCLUDES 	+= -Iinclude \
#	           -I/usr/include

LIBPATHS	+= $(BLDROOT)/$(MTARGET)/lib \



REQUIRE_PCRE = 1

include $(MAKE_HOME)/makefile.incl
include $(MAKE_HOME)/makefile.exec

