// -*- C++ -*-
#if !defined( NET_INPUTS_H )
#define NET_INPUTS_H

/*
 * net_inputs.h
 *
 * by Joseph Heled, 2002
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#if defined( __GNUG__ )
#pragma interface
#endif

#include "bgdefs.h"

class NeuralNet;

//@ Neural Net for supported positions types.
//  Each function is actually in the file for that specific net, but since
//  those files are generated by @ref{net_to_c.tcl}, I choose to put the
//  prototypes here.

///
extern const NeuralNet* bearoffGetNet(void);
///
extern const NeuralNet* raceGetNet(void);
///
extern const NeuralNet* contactGetNet(void);
///
extern const NeuralNet* crashedGetNet(void);

//@ Neural Net input generators for supported positions types.

///
extern void  bearoffGetInputs(BG::Board const& b, float* inputs);
///
extern void  raceGetInputs(BG::Board const& b, float* inputs);
///
extern void  contactGetInputs(BG::Board const& b, float* inputs);
///
extern void  crashedGetInputs(BG::Board const& b, float* inputs);

#endif
