// -*- C++ -*-
#if !defined( SANITY_H )
#define SANITY_H

#include "bgdefs.h"

namespace BG {
/// Generic sanity checking for probabilities generated by the NN for
/// @arg{board}.
//  If gammon or backgammon are impossible, set respective probabilities to
//  zero. Chack that gammon/backgammon% are smaller than win%.
//
void
genericSanity(Board const& board, CubelessProbs probs);

/// Sanity checks for race.
//  
//  Compute backgammon rate using a direct method, then call
//  @ref{genericSanity}.
//
void
raceSanity(Board const& board, CubelessProbs probs, Evaluator& bearoff);

}

#endif
