
DIR = speed
EXE = speed
SRCS = 	speed.cpp \
	ping.cpp 

EXTRA_INCLUDES 	+= -Iinclude 

EXTRALIBPATHS	+= $(BLDROOT)/$(MTARGET)/lib 


include $(MAKE_HOME)/makefile.incl
include $(MAKE_HOME)/makefile.exec

