
DIR = debug
LIB = debug
SRCS = 	debug.cpp 

EXTRA_INCLUDES 	+= -I$(SRCROOT)/color/include \
	           -I.

EXTRALIBPATHS	+= $(BLDROOT)/$(MTARGET)/lib 


include $(MAKE_HOME)/makefile.incl
include $(MAKE_HOME)/makefile.lib

