######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 16 15:46:29 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += dejarik.cpp
