DIR = getter
EXE = getter
SRCS = 	getter.cpp 

EXTRA_INCLUDES 	+= -Iinclude \
	           -I$(SRCROOT)/third_party/boost

LIBPATHS	+= $(BLDROOT)/$(MTARGET)/lib 		


include $(MAKE_HOME)/makefile.incl
include $(MAKE_HOME)/makefile.exec

